"""초대 코드 테이블과 users.invite_code_id

가입을 열어 두면 도메인을 찾은 누구나 홈서버 컨테이너 안에서 코드를 실행할 수
있다. 코드는 SHA-256 으로 저장한다 — argon2 는 솔트 때문에 해시로 조회할 수
없어 가입 시도마다 전수 검증이 되고, 그 자체가 DoS 벡터가 된다.


Revision ID: 999772efcca9
Revises: f2a83c33b614
Create Date: 2026-08-11 22:20:54.941542

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '999772efcca9'
down_revision: Union[str, Sequence[str], None] = 'f2a83c33b614'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('invite_codes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code_hash', sa.String(length=64), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('max_uses', sa.Integer(), nullable=False),
    sa.Column('used_count', sa.Integer(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint('max_uses > 0', name='ck_invite_codes_max_uses'),
    sa.CheckConstraint('used_count >= 0', name='ck_invite_codes_used_count'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_invite_codes_code_hash'), 'invite_codes', ['code_hash'], unique=True)
    op.add_column('users', sa.Column('invite_code_id', sa.Integer(), nullable=True))
    op.create_foreign_key(
        'fk_users_invite_code_id',
        'users',
        'invite_codes',
        ['invite_code_id'],
        ['id'],
        ondelete='SET NULL',
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_users_invite_code_id', 'users', type_='foreignkey')
    op.drop_column('users', 'invite_code_id')
    op.drop_index(op.f('ix_invite_codes_code_hash'), table_name='invite_codes')
    op.drop_table('invite_codes')
    # ### end Alembic commands ###
